name: Deploy HTML Docs to GitHub Pages


on: [push]
#on:
#  push:
#    branches: [main]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv package manager
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install system libraries
        run: |
          sudo apt update
          sudo apt install -y \
            libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev gcc \
            qtbase5-dev qtchooser qttools5-dev-tools qttools5-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Python project dependencies
        run: uv pip install --system .

      - name: Install pdoc
        run: uv pip install --system pdoc

      - name: Generate docs
        run: pdoc src/creatumlibre --output-dir docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs

      - name: Generate custom index
        run: python scripts/generate_index.py
